/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../lib/api-client';




/**
 * Solicita código de login via email (para usuários normais)
 */
export const apiUsersLoginRequestCodeCreate = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/users/login/request-code/`, method: 'POST', signal
    },
      );
    }
  


export const getApiUsersLoginRequestCodeCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersLoginRequestCodeCreate>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof apiUsersLoginRequestCodeCreate>>, TError,void, TContext> => {

const mutationKey = ['apiUsersLoginRequestCodeCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiUsersLoginRequestCodeCreate>>, void> = () => {
          

          return  apiUsersLoginRequestCodeCreate()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiUsersLoginRequestCodeCreateMutationResult = NonNullable<Awaited<ReturnType<typeof apiUsersLoginRequestCodeCreate>>>
    
    export type ApiUsersLoginRequestCodeCreateMutationError = unknown

    export const useApiUsersLoginRequestCodeCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersLoginRequestCodeCreate>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof apiUsersLoginRequestCodeCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getApiUsersLoginRequestCodeCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Faz login usando código recebido por email
 */
export const apiUsersLoginVerifyCodeCreate = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/users/login/verify-code/`, method: 'POST', signal
    },
      );
    }
  


export const getApiUsersLoginVerifyCodeCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersLoginVerifyCodeCreate>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof apiUsersLoginVerifyCodeCreate>>, TError,void, TContext> => {

const mutationKey = ['apiUsersLoginVerifyCodeCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiUsersLoginVerifyCodeCreate>>, void> = () => {
          

          return  apiUsersLoginVerifyCodeCreate()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiUsersLoginVerifyCodeCreateMutationResult = NonNullable<Awaited<ReturnType<typeof apiUsersLoginVerifyCodeCreate>>>
    
    export type ApiUsersLoginVerifyCodeCreateMutationError = unknown

    export const useApiUsersLoginVerifyCodeCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersLoginVerifyCodeCreate>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof apiUsersLoginVerifyCodeCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getApiUsersLoginVerifyCodeCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Login apenas para superusers (admins) com email e senha
 */
export const apiUsersTokenCreate = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/users/token/`, method: 'POST', signal
    },
      );
    }
  


export const getApiUsersTokenCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersTokenCreate>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof apiUsersTokenCreate>>, TError,void, TContext> => {

const mutationKey = ['apiUsersTokenCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiUsersTokenCreate>>, void> = () => {
          

          return  apiUsersTokenCreate()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiUsersTokenCreateMutationResult = NonNullable<Awaited<ReturnType<typeof apiUsersTokenCreate>>>
    
    export type ApiUsersTokenCreateMutationError = unknown

    export const useApiUsersTokenCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersTokenCreate>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof apiUsersTokenCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getApiUsersTokenCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const apiUsersTokenRevokeCreate = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/users/token/revoke/`, method: 'POST', signal
    },
      );
    }
  


export const getApiUsersTokenRevokeCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersTokenRevokeCreate>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof apiUsersTokenRevokeCreate>>, TError,void, TContext> => {

const mutationKey = ['apiUsersTokenRevokeCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiUsersTokenRevokeCreate>>, void> = () => {
          

          return  apiUsersTokenRevokeCreate()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiUsersTokenRevokeCreateMutationResult = NonNullable<Awaited<ReturnType<typeof apiUsersTokenRevokeCreate>>>
    
    export type ApiUsersTokenRevokeCreateMutationError = unknown

    export const useApiUsersTokenRevokeCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersTokenRevokeCreate>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof apiUsersTokenRevokeCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getApiUsersTokenRevokeCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Return data from user.
 */
export const apiUsersUserRetrieve = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/users/user/`, method: 'GET', signal
    },
      );
    }
  



export const getApiUsersUserRetrieveQueryKey = () => {
    return [
    `/api/users/user/`
    ] as const;
    }

    
export const getApiUsersUserRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof apiUsersUserRetrieve>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof apiUsersUserRetrieve>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiUsersUserRetrieveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiUsersUserRetrieve>>> = ({ signal }) => apiUsersUserRetrieve(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiUsersUserRetrieve>>, TError, TData> & { queryKey: QueryKey }
}

export type ApiUsersUserRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof apiUsersUserRetrieve>>>
export type ApiUsersUserRetrieveQueryError = unknown



export function useApiUsersUserRetrieve<TData = Awaited<ReturnType<typeof apiUsersUserRetrieve>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof apiUsersUserRetrieve>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getApiUsersUserRetrieveQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new user.
 */
export const apiUsersUserCreate = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/users/user/`, method: 'POST', signal
    },
      );
    }
  


export const getApiUsersUserCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserCreate>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserCreate>>, TError,void, TContext> => {

const mutationKey = ['apiUsersUserCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiUsersUserCreate>>, void> = () => {
          

          return  apiUsersUserCreate()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiUsersUserCreateMutationResult = NonNullable<Awaited<ReturnType<typeof apiUsersUserCreate>>>
    
    export type ApiUsersUserCreateMutationError = unknown

    export const useApiUsersUserCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserCreate>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof apiUsersUserCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getApiUsersUserCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Update user data.
 */
export const apiUsersUserPartialUpdate = (
    
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/users/user/`, method: 'PATCH'
    },
      );
    }
  


export const getApiUsersUserPartialUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserPartialUpdate>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserPartialUpdate>>, TError,void, TContext> => {

const mutationKey = ['apiUsersUserPartialUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiUsersUserPartialUpdate>>, void> = () => {
          

          return  apiUsersUserPartialUpdate()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiUsersUserPartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof apiUsersUserPartialUpdate>>>
    
    export type ApiUsersUserPartialUpdateMutationError = unknown

    export const useApiUsersUserPartialUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserPartialUpdate>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof apiUsersUserPartialUpdate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getApiUsersUserPartialUpdateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Confirma email do usuário e ativa a conta automaticamente
 */
export const apiUsersUserConfirmEmailCreate = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/users/user/confirm-email/`, method: 'POST', signal
    },
      );
    }
  


export const getApiUsersUserConfirmEmailCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserConfirmEmailCreate>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserConfirmEmailCreate>>, TError,void, TContext> => {

const mutationKey = ['apiUsersUserConfirmEmailCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiUsersUserConfirmEmailCreate>>, void> = () => {
          

          return  apiUsersUserConfirmEmailCreate()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiUsersUserConfirmEmailCreateMutationResult = NonNullable<Awaited<ReturnType<typeof apiUsersUserConfirmEmailCreate>>>
    
    export type ApiUsersUserConfirmEmailCreateMutationError = unknown

    export const useApiUsersUserConfirmEmailCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserConfirmEmailCreate>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof apiUsersUserConfirmEmailCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getApiUsersUserConfirmEmailCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const apiUsersUserPasswordResetCreate = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/users/user/password_reset/`, method: 'POST', signal
    },
      );
    }
  


export const getApiUsersUserPasswordResetCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserPasswordResetCreate>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserPasswordResetCreate>>, TError,void, TContext> => {

const mutationKey = ['apiUsersUserPasswordResetCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiUsersUserPasswordResetCreate>>, void> = () => {
          

          return  apiUsersUserPasswordResetCreate()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiUsersUserPasswordResetCreateMutationResult = NonNullable<Awaited<ReturnType<typeof apiUsersUserPasswordResetCreate>>>
    
    export type ApiUsersUserPasswordResetCreateMutationError = unknown

    export const useApiUsersUserPasswordResetCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserPasswordResetCreate>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof apiUsersUserPasswordResetCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getApiUsersUserPasswordResetCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const apiUsersUserPasswordResetConfirmCreate = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/users/user/password_reset/confirm/`, method: 'POST', signal
    },
      );
    }
  


export const getApiUsersUserPasswordResetConfirmCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserPasswordResetConfirmCreate>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserPasswordResetConfirmCreate>>, TError,void, TContext> => {

const mutationKey = ['apiUsersUserPasswordResetConfirmCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiUsersUserPasswordResetConfirmCreate>>, void> = () => {
          

          return  apiUsersUserPasswordResetConfirmCreate()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiUsersUserPasswordResetConfirmCreateMutationResult = NonNullable<Awaited<ReturnType<typeof apiUsersUserPasswordResetConfirmCreate>>>
    
    export type ApiUsersUserPasswordResetConfirmCreateMutationError = unknown

    export const useApiUsersUserPasswordResetConfirmCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserPasswordResetConfirmCreate>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof apiUsersUserPasswordResetConfirmCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getApiUsersUserPasswordResetConfirmCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const apiUsersUserResendEmailConfirmationCreate = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/users/user/resend-email-confirmation/`, method: 'POST', signal
    },
      );
    }
  


export const getApiUsersUserResendEmailConfirmationCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserResendEmailConfirmationCreate>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserResendEmailConfirmationCreate>>, TError,void, TContext> => {

const mutationKey = ['apiUsersUserResendEmailConfirmationCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiUsersUserResendEmailConfirmationCreate>>, void> = () => {
          

          return  apiUsersUserResendEmailConfirmationCreate()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiUsersUserResendEmailConfirmationCreateMutationResult = NonNullable<Awaited<ReturnType<typeof apiUsersUserResendEmailConfirmationCreate>>>
    
    export type ApiUsersUserResendEmailConfirmationCreateMutationError = unknown

    export const useApiUsersUserResendEmailConfirmationCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersUserResendEmailConfirmationCreate>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof apiUsersUserResendEmailConfirmationCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getApiUsersUserResendEmailConfirmationCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    