/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from '../../lib/api-client';



  export const getAuth = () => {
/**
 * Solicita código de login via email (para usuários normais)
 */
const apiUsersLoginRequestCodeCreate = (
    
 ) => {
      return customInstance<void>(
      {url: `/api/users/login/request-code/`, method: 'POST'
    },
      );
    }
  /**
 * Faz login usando código recebido por email
 */
const apiUsersLoginVerifyCodeCreate = (
    
 ) => {
      return customInstance<void>(
      {url: `/api/users/login/verify-code/`, method: 'POST'
    },
      );
    }
  /**
 * Login apenas para superusers (admins) com email e senha
 */
const apiUsersTokenCreate = (
    
 ) => {
      return customInstance<void>(
      {url: `/api/users/token/`, method: 'POST'
    },
      );
    }
  const apiUsersTokenRevokeCreate = (
    
 ) => {
      return customInstance<void>(
      {url: `/api/users/token/revoke/`, method: 'POST'
    },
      );
    }
  /**
 * Return data from user.
 */
const apiUsersUserRetrieve = (
    
 ) => {
      return customInstance<void>(
      {url: `/api/users/user/`, method: 'GET'
    },
      );
    }
  /**
 * Create a new user.
 */
const apiUsersUserCreate = (
    
 ) => {
      return customInstance<void>(
      {url: `/api/users/user/`, method: 'POST'
    },
      );
    }
  /**
 * Update user data.
 */
const apiUsersUserPartialUpdate = (
    
 ) => {
      return customInstance<void>(
      {url: `/api/users/user/`, method: 'PATCH'
    },
      );
    }
  /**
 * Confirma email do usuário e ativa a conta automaticamente
 */
const apiUsersUserConfirmEmailCreate = (
    
 ) => {
      return customInstance<void>(
      {url: `/api/users/user/confirm-email/`, method: 'POST'
    },
      );
    }
  const apiUsersUserResendEmailConfirmationCreate = (
    
 ) => {
      return customInstance<void>(
      {url: `/api/users/user/resend-email-confirmation/`, method: 'POST'
    },
      );
    }
  return {apiUsersLoginRequestCodeCreate,apiUsersLoginVerifyCodeCreate,apiUsersTokenCreate,apiUsersTokenRevokeCreate,apiUsersUserRetrieve,apiUsersUserCreate,apiUsersUserPartialUpdate,apiUsersUserConfirmEmailCreate,apiUsersUserResendEmailConfirmationCreate}};
export type ApiUsersLoginRequestCodeCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['apiUsersLoginRequestCodeCreate']>>>
export type ApiUsersLoginVerifyCodeCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['apiUsersLoginVerifyCodeCreate']>>>
export type ApiUsersTokenCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['apiUsersTokenCreate']>>>
export type ApiUsersTokenRevokeCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['apiUsersTokenRevokeCreate']>>>
export type ApiUsersUserRetrieveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['apiUsersUserRetrieve']>>>
export type ApiUsersUserCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['apiUsersUserCreate']>>>
export type ApiUsersUserPartialUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['apiUsersUserPartialUpdate']>>>
export type ApiUsersUserConfirmEmailCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['apiUsersUserConfirmEmailCreate']>>>
export type ApiUsersUserResendEmailConfirmationCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['apiUsersUserResendEmailConfirmationCreate']>>>
