/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */

export type ApiExperimentsAnalysisRetrieveParams = {
/**
 * Nome da variável de resposta a analisar
 */
response?: string;
};
