/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */
import type { DesignTypeEnum } from './designTypeEnum';
import type { StatusEnum } from './statusEnum';

/**
 * Serializer completo para detalhes do experimento.
 */
export interface ExperimentDetail {
  readonly id: number;
  /** @pattern ^[-a-zA-Z0-9_]+$ */
  readonly slug: string;
  /** @maxLength 200 */
  title: string;
  description?: string;
  design_type?: DesignTypeEnum;
  status?: StatusEnum;
  readonly owner: number;
  readonly owner_email: string;
  readonly owner_name: string;
  readonly created_at: string;
  readonly updated_at: string;
}
