/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */
import type { DesignTypeEnum } from './designTypeEnum';
import type { StatusEnum } from './statusEnum';

/**
 * Serializer para atualização de experimentos.
 */
export interface ExperimentUpdate {
  /** @maxLength 200 */
  title: string;
  description?: string;
  design_type?: DesignTypeEnum;
  status?: StatusEnum;
}
