/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer completo para detalhes do run.
 */
export interface ExperimentRunDetail {
  readonly id: number;
  /**
   * Order in the standard design matrix
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  standard_order: number;
  /**
   * Randomized order of execution
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  run_order: number;
  /** Whether this run is a center point (for replication) */
  is_center_point?: boolean;
  /** Dictionary mapping factor IDs to their values for this run */
  factor_values?: unknown;
  /** Dictionary mapping response variable IDs to their measured values */
  response_values?: unknown;
  /** Whether to exclude this run from analysis (e.g., outlier) */
  is_excluded?: boolean;
  readonly experiment: number;
  readonly experiment_title: string;
  /** @pattern ^[-a-zA-Z0-9_]+$ */
  readonly experiment_slug: string;
  readonly has_responses: string;
  readonly is_complete: string;
  readonly created_at: string;
  readonly updated_at: string;
}
