/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */
import type { DesignTypeEnum } from './designTypeEnum';

/**
 * Serializer para criação de experimentos.
 */
export interface ExperimentCreate {
  /** @pattern ^[-a-zA-Z0-9_]+$ */
  readonly slug: string;
  /** @maxLength 200 */
  title: string;
  description?: string;
  design_type?: DesignTypeEnum;
  /**
   * Number of replicates for each factor combination
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  replicates?: number;
}
