/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer para atualização de runs.
 */
export interface ExperimentRunUpdate {
  /**
   * Order in the standard design matrix
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  standard_order: number;
  /**
   * Randomized order of execution
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  run_order: number;
  /** Whether this run is a center point (for replication) */
  is_center_point?: boolean;
  /** Dictionary mapping factor IDs to their values for this run */
  factor_values?: unknown;
  /** Dictionary mapping response variable IDs to their measured values */
  response_values?: unknown;
  /** Whether to exclude this run from analysis (e.g., outlier) */
  is_excluded?: boolean;
}
