/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer simplificado para listagem de runs.
 */
export interface ExperimentRunList {
  readonly id: number;
  /**
   * Order in the standard design matrix
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  standard_order: number;
  /**
   * Randomized order of execution
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  run_order: number;
  /** Whether this run is a center point (for replication) */
  is_center_point?: boolean;
  /** Whether to exclude this run from analysis (e.g., outlier) */
  is_excluded?: boolean;
  readonly has_responses: string;
  readonly is_complete: string;
  readonly created_at: string;
  readonly updated_at: string;
}
