/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */
import type { DataTypeEnum } from './dataTypeEnum';

/**
 * Serializer simplificado para listagem de fatores.
 */
export interface FactorList {
  readonly id: number;
  /** @maxLength 100 */
  name: string;
  /** @maxLength 20 */
  symbol: string;
  data_type?: DataTypeEnum;
  readonly created_at: string;
  readonly updated_at: string;
}
