/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */
import type { DataTypeEnum } from './dataTypeEnum';

/**
 * Serializer para atualização de fatores.
 */
export interface PatchedFactorUpdate {
  /** @maxLength 100 */
  name?: string;
  /** @maxLength 20 */
  symbol?: string;
  data_type?: DataTypeEnum;
  /**
   * Number of decimal places for quantitative factors
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  precision?: number;
  /** JSON with levels configuration */
  levels_config?: unknown;
}
