/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */
import type { OptimizationGoalEnum } from './optimizationGoalEnum';

/**
 * Serializer completo para detalhes da variável de resposta.
 */
export interface ResponseVariableDetail {
  readonly id: number;
  /** @maxLength 100 */
  name: string;
  /**
   * Unit of measurement (e.g., kg, °C, %)
   * @maxLength 50
   */
  unit?: string;
  /** Whether to maximize, minimize, or target this response

* `maximize` - Maximize
* `minimize` - Minimize
* `target` - Target
* `none` - Nenhum(a/as) */
  optimization_goal?: OptimizationGoalEnum;
  readonly experiment: number;
  readonly experiment_title: string;
  /** @pattern ^[-a-zA-Z0-9_]+$ */
  readonly experiment_slug: string;
  readonly created_at: string;
  readonly updated_at: string;
}
