/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer para criação de variáveis de resposta.
 */
export interface ResponseVariableCreate {
  /** @maxLength 100 */
  name: string;
  /**
   * Unit of measurement (e.g., kg, °C, %)
   * @maxLength 50
   */
  unit?: string;
}
