/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */

export interface TokenRefresh {
  readonly access: string;
  refresh: string;
}
