/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */
import type {
  RootRetrieve200
} from '../../types';

import { customInstance } from '../../lib/api-client';



  export const getCore = () => {
/**
 * Lista todos os endpoints e recursos disponíveis no sistema.
 * @summary Navegação da API (Root)
 */
const rootRetrieve = (
    
 ) => {
      return customInstance<RootRetrieve200>(
      {url: `/`, method: 'GET'
    },
      );
    }
  return {rootRetrieve}};
export type RootRetrieveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCore>['rootRetrieve']>>>
