/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * Documentação automática da API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  TokenRefresh
} from '../../types';

import { customInstance } from '../../lib/api-client';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;





/**
 * Takes a refresh type JSON web token and returns an access type JSON web
token if the refresh token is valid.
 */
export const apiUsersTokenRefreshCreate = (
    tokenRefresh: NonReadonly<TokenRefresh>,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TokenRefresh>(
      {url: `/api/users/token/refresh/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tokenRefresh, signal
    },
      );
    }
  


export const getApiUsersTokenRefreshCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersTokenRefreshCreate>>, TError,{data: NonReadonly<TokenRefresh>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof apiUsersTokenRefreshCreate>>, TError,{data: NonReadonly<TokenRefresh>}, TContext> => {

const mutationKey = ['apiUsersTokenRefreshCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiUsersTokenRefreshCreate>>, {data: NonReadonly<TokenRefresh>}> = (props) => {
          const {data} = props ?? {};

          return  apiUsersTokenRefreshCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiUsersTokenRefreshCreateMutationResult = NonNullable<Awaited<ReturnType<typeof apiUsersTokenRefreshCreate>>>
    export type ApiUsersTokenRefreshCreateMutationBody = NonReadonly<TokenRefresh>
    export type ApiUsersTokenRefreshCreateMutationError = unknown

    export const useApiUsersTokenRefreshCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiUsersTokenRefreshCreate>>, TError,{data: NonReadonly<TokenRefresh>}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof apiUsersTokenRefreshCreate>>,
        TError,
        {data: NonReadonly<TokenRefresh>},
        TContext
      > => {

      const mutationOptions = getApiUsersTokenRefreshCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    