# Generated by Django 5.1 on 2025-11-29 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='login code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='login code expires at'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT_PAYMENT', 'Crédito via Pagamento'), ('CREDIT_MANUAL', 'Crédito Manual'), ('DEBIT_SERVICE', 'Débito - Consumo de Serviço'), ('REFUND', 'Estorno')], max_length=20, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('admin_notes', models.TextField(blank=True, help_text='Observações internas sobre a transação', verbose_name='admin notes')),
                ('added_by', models.ForeignKey(blank=True, help_text='Administrador que adicionou o crédito manualmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_transactions_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
